server:
  port: 9090


spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:file:~/oauth
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true


  flyway:
    enabled: true
    locations: classpath:db/h2
    baseline-on-migrate: true


logging:
  level:
    org:
      hibernate:
        type: trace
